# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 714d473f7b43838da141195e2e2dc2a204bb2933f11971daf3a33553de6d83a572d5a0ac2a2ab7e52b5aa798681d3e331ea6e7eeef8c0df81ebdf5909ea342b1

test:
  secret_key_base: a3fad5ea3902999834dfff46d6f2fd794937b15eed0ede84dda3c4ca60def18a0178aff8f663d4ee5e959c836b2a462553985759793b208c668515ce065a541f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
